# Generated by Django 6.0.7 on 2026-07-14 18:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationCaptcha',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'registration_captchas',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='analyst_status',
            field=models.CharField(default='none', max_length=20, verbose_name='审核状态'),
        ),
    ]
