# Generated by Django 6.0.7 on 2026-07-14 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_registrationcaptcha_userprofile_analyst_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationCaptcha',
        ),
    ]
