# Generated by Django 6.0.7 on 2026-07-12 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articleinstrumentrelation',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.article'),
        ),
        migrations.AddField(
            model_name='articleinstrumentrelation',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.marketinstrument'),
        ),
        migrations.AddField(
            model_name='article',
            name='instruments',
            field=models.ManyToManyField(through='news.ArticleInstrumentRelation', to='market.marketinstrument'),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='news.article'),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articletagrelation',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.article'),
        ),
        migrations.AddField(
            model_name='articletopicrelation',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.article'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='news.category'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='articles', to='news.category'),
        ),
        migrations.AddField(
            model_name='livenews',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livenewsinstrumentrelation',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.marketinstrument'),
        ),
        migrations.AddField(
            model_name='livenewsinstrumentrelation',
            name='live_news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.livenews'),
        ),
        migrations.AddField(
            model_name='livenews',
            name='instruments',
            field=models.ManyToManyField(through='news.LiveNewsInstrumentRelation', to='market.marketinstrument'),
        ),
        migrations.AddField(
            model_name='specialtopic',
            name='articles',
            field=models.ManyToManyField(through='news.ArticleTopicRelation', to='news.article'),
        ),
        migrations.AddField(
            model_name='articletopicrelation',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.specialtopic'),
        ),
        migrations.AddField(
            model_name='articletagrelation',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.tag'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(through='news.ArticleTagRelation', to='news.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='articleinstrumentrelation',
            unique_together={('article', 'instrument')},
        ),
        migrations.AlterUniqueTogether(
            name='articlerevision',
            unique_together={('article', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='livenews',
            unique_together={('id', 'publish_time')},
        ),
        migrations.AlterUniqueTogether(
            name='articletopicrelation',
            unique_together={('article', 'topic')},
        ),
        migrations.AlterUniqueTogether(
            name='articletagrelation',
            unique_together={('article', 'tag')},
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', 'publish_at'], name='idx_art_status_pub'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['importance'], name='idx_art_importance'),
        ),
    ]
