# Generated by Django 6.0.7 on 2026-07-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livenews',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
