# Generated by Django 6.0.7 on 2026-07-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_article_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='livenews',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
