# Generated by Django 6.0.7 on 2026-07-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_article_source_url_livenews_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_articles',
            field=models.ManyToManyField(blank=True, to='news.article'),
        ),
    ]
