# Generated by Django 6.0.7 on 2026-07-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_article_allow_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livenews',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
