# Generated by Django

from django.db import migrations

def migrate_and_clean_categories(apps, schema_editor):
    Category = apps.get_model('news', 'Category')
    Article = apps.get_model('news', 'Article')

    mapping = {
        '前沿科技': 'Frontier Tech',
        '独角兽动态': 'Unicorn Dynamics',
        'VC/PE观察': 'VC/PE Insights'
    }

    for zh_name, en_name in mapping.items():
        en_cat = Category.objects.filter(name=en_name).first()
        zh_cat = Category.objects.filter(name=zh_name).first()

        if zh_cat:
            if not en_cat:
                # 如果英文分类不存在，直接将中文分类改名并更新 slug
                zh_cat.name = en_name
                zh_cat.slug = en_name.lower().replace(' ', '-').replace('/', '-')
                zh_cat.save()
            else:
                # 如果英文分类已存在，将所有关联文章转移到英文分类，并删除中文分类
                Article.objects.filter(category=zh_cat).update(category=en_cat)
                zh_cat.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_livenews_is_approved'),
    ]

    operations = [
        migrations.RunPython(migrate_and_clean_categories),
    ]
