# Generated by Django 6.0.7 on 2026-07-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('class_type', models.CharField(choices=[('stock', '股票'), ('bond', '债券'), ('forex', '外汇'), ('commodity', '大宗商品'), ('crypto', '加密货币'), ('index', '指数')], db_column='class', max_length=30)),
                ('exchange', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'market_instruments',
                'indexes': [models.Index(fields=['class_type'], name='idx_inst_class')],
            },
        ),
    ]
