# Generated by Django 6.0.7 on 2026-07-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('round', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=100)),
                ('investor', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'funding_deals',
                'ordering': ['-id'],
            },
        ),
    ]
